export const GETTED_ALL_CONTACTS_SUCCESS = 'GETTED_ALL_CONTACTS_SUCCESS'
export const GETTED_ALL_CONTACTS_FAILED = 'GETTED_ALL_CONTACTS_FAILED'
export const REMOVE_CONTACT_FAILED = 'REMOVE_CONTACT_FAILED'
